<?php

declare(strict_types = 1);

namespace App\Controller;

use Cake\Controller\Controller;
use Cake\Event\EventInterface;
use Cake\I18n\I18n;
use Cake\Utility\Hash;

/**
 * Application Controller
 *
 * Add your application-wide methods in the class below, your controllers
 * will inherit them.
 *
 * @link https://book.cakephp.org/4/en/controllers.html#the-app-controller
 */
class AppController extends Controller
{
    /**
     * Initialization hook method.
     *
     * Use this method to add common initialization code like loading components.
     *
     * e.g. `$this->loadComponent('FormProtection');`
     *
     * @return void
     * @throws \Exception
     */
    public function initialize(): void
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
    }

    /**
     * beforeFilter method
     *
     * @param  EventInterface  $event
     *
     * @return \Cake\Http\Response|void|null
     */
    public function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub

        if (!is_null($this->request->getCookie('locale'))) {
            I18n::setLocale($this->request->getCookie('locale'));
        } else {
            setcookie('locale', 'en_US', time() + (86400 * 30), "/");
        }
    }

    /**
     * beforeRender method
     *
     * @param  EventInterface  $event
     *
     * @return \Cake\Http\Response|void|null
     */
    public function beforeRender(\Cake\Event\EventInterface $event)
    {
        if ($this->request->is('mobile')) {
            $this->viewBuilder()->setTheme('Mobile');
        } else {
            $this->viewBuilder()->setTheme('Desktop');
        }
    }
}
